# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target 'PhotoSharingApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SDWebImage'
  
  # Pods for PhotoSharingApp

  target 'PhotoSharingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
